export const BRAND_LOGOS = [
  { name: 'Brand 1',  logo: '/brands/b1.png' },
  { name: 'Brand 2',  logo: '/brands/b2.png' },
  { name: 'Brand 3',  logo: '/brands/b3.png' },
  { name: 'Brand 4',  logo: '/brands/b4.png' },
  { name: 'Brand 5',  logo: '/brands/b5.png' },
  { name: 'Brand 6',  logo: '/brands/b6.png' },
  { name: 'Brand 7',  logo: '/brands/b7.png' },
  { name: 'Brand 8',  logo: '/brands/b8.png' },
  { name: 'Brand 9',  logo: '/brands/b9.png' },
  { name: 'Brand 10', logo: '/brands/b10.png' },
  { name: 'Brand 11', logo: '/brands/b11.png' },
  { name: 'Brand 12', logo: '/brands/b12.png' },
  { name: 'Brand 13', logo: '/brands/b13.png' },
  { name: 'Brand 14', logo: '/brands/b14.png' },
  { name: 'Brand 15', logo: '/brands/b15.png' },
  { name: 'Brand 16', logo: '/brands/b16.png' },
];
